version: '3'

services:
    redis:
        image: redis:alpine

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sandbod
        ports:
            - 3306:3306
        volumes:
            - myvolume:/var/lib/mysql

    restapi:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./restapi:/django
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DEBUG: "true"
            DATABASE_HOST: db
            REDIS_SERVICE_HOST: redis://redis:6379

volumes:
    myvolume:
