# Generated by Django 3.2 on 2022-03-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimaticCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('temp', models.FloatField(help_text='main temperature')),
                ('temp_min', models.FloatField(help_text='minimum temperature')),
                ('temp_max', models.FloatField(help_text='maximum temperature')),
                ('pressure', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteorology.city')),
            ],
        ),
    ]
